// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    world_debt_solution
    (
        init => init
        upgrade => upgrade
        getSum => sum
        add => add
        set_debt => set_debt
        increase_debt => increase_debt
        decrease_debt => decrease_debt
        get_debt => get_debt
        draw_from_reserves => draw_from_reserves
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
